import { test, expect } from '@playwright/test';
import { randomBytes } from 'node:crypto';

test('public portfolio filters projects and opens an accessible detail dialog', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { level: 1 })).toContainText('당신의 브랜드에');
  await expect(page.locator('.project-card')).toHaveCount(4);
  await page.locator('.work-filters').getByRole('button', { name: '웹사이트', exact: true }).click();
  await expect(page.locator('.project-card')).toHaveCount(2);
  await page.locator('.work-filters').getByRole('button', { name: '브랜딩', exact: true }).click();
  await expect(page.locator('.project-card')).toHaveCount(1);
  await page.locator('.work-filters').getByRole('button', { name: '커머스', exact: true }).click();
  await expect(page.locator('.project-card')).toHaveCount(1);
  await page.locator('.work-filters').getByRole('button', { name: /^전체/ }).click();
  const opener = page.getByRole('button', { name: '오브제 커피 상세 보기' });
  await opener.click();
  const dialog = page.getByRole('dialog', { name: '오브제 커피' });
  await expect(dialog).toBeVisible();
  await expect(dialog).toContainText('가상의 프로젝트');
  await expect(dialog).toContainText('2026');
  const close = dialog.getByRole('button', { name: '프로젝트 상세 닫기' });
  await expect(close).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(close).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  await expect(close).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(opener).toBeFocused();
  expect(errors).toEqual([]);
});

test('mobile navigation and layout stay usable without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.locator('.project-card')).toHaveCount(4);
  const toggle = page.getByRole('button', { name: '메뉴 열기' });
  await toggle.click();
  await expect(page.getByRole('navigation', { name: '주 메뉴' })).toBeVisible();
  await page.getByRole('navigation', { name: '주 메뉴' }).getByRole('link', { name: 'Services' }).click();
  await expect(page.getByRole('button', { name: '메뉴 열기' })).toHaveAttribute('aria-expanded', 'false');
  await expect(page.locator('#services')).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: '모먼트 뷰티 상세 보기' }).click();
  const detail = page.getByRole('dialog', { name: '모먼트 뷰티' });
  await expect(detail).toBeVisible();
  await detail.getByRole('button', { name: '프로젝트 상세 닫기' }).click();
  await expect(detail).not.toBeVisible();
});

test('admin sets a password, validates, creates, reads, updates, deletes and signs in again', async ({ page }) => {
  const password = `e2e-only-${randomBytes(16).toString('hex')}`;
  const title = `브라우저 검증 ${Date.now()}`;
  const updatedTitle = `${title} 수정`;
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/admin');
  await page.getByLabel('새 관리자 비밀번호', { exact: true }).fill(password);
  await page.getByLabel('비밀번호 확인', { exact: true }).fill(password);
  await page.getByRole('button', { name: '비밀번호 설정하고 시작하기' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toContainText('작업을 모으는 공간');
  await expect(page.locator('.admin-project-row')).toHaveCount(4);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: 'test-results/admin-preview.png' });
  await page.getByRole('button', { name: '새 프로젝트', exact: true }).click();
  let editor = page.getByRole('dialog', { name: '새 프로젝트', exact: true });
  await editor.getByRole('button', { name: '프로젝트 저장' }).click();
  await expect(editor).toContainText('프로젝트 이름을 입력해 주세요.');
  await editor.getByLabel(/프로젝트 이름/).fill(title);
  await editor.getByLabel('한 줄 소개').fill('임시 데이터로 확인하는 실제 등록 흐름');
  await editor.getByLabel(/분야/).selectOption('브랜딩');
  await editor.getByLabel(/작업 연도/).fill('2026');
  await editor.getByLabel(/프로젝트 소개/).fill('프로젝트 등록부터 공개, 수정, 삭제까지 확인합니다.');
  await editor.getByLabel('고객사').fill('테스트 전용');
  await editor.getByLabel('태그', { exact: true }).fill('디자인, 개발');
  await editor.getByLabel('커버 이미지').selectOption('beauty');
  await editor.getByRole('button', { name: '프로젝트 저장' }).click();
  await expect(editor).not.toBeVisible();
  await expect(page.locator('.admin-project-row')).toHaveCount(5);
  let row = page.locator('.admin-project-row').filter({ has: page.getByRole('button', { name: title, exact: true }) });
  await expect(row).toContainText('초안');
  let projects = await (await page.request.get('/api/projects')).json();
  expect(projects.projects.some((project: { title: string }) => project.title === title)).toBe(false);
  await page.reload();
  row = page.locator('.admin-project-row').filter({ has: page.getByRole('button', { name: title, exact: true }) });
  await expect(row).toBeVisible();
  await row.getByRole('button', { name: '수정', exact: true }).click();
  editor = page.getByRole('dialog', { name: '프로젝트 수정', exact: true });
  await expect(editor.getByLabel(/프로젝트 이름/)).toHaveValue(title);
  await editor.getByLabel(/프로젝트 이름/).fill(updatedTitle);
  await editor.getByLabel(/포트폴리오에 공개/).check();
  await editor.getByLabel(/추천 프로젝트/).check();
  await editor.getByRole('button', { name: '프로젝트 저장' }).click();
  await expect(editor).not.toBeVisible();
  row = page.locator('.admin-project-row').filter({ has: page.getByRole('button', { name: updatedTitle, exact: true }) });
  await expect(row).toContainText('공개 중');
  projects = await (await page.request.get('/api/projects')).json();
  const published = projects.projects.find((project: { title: string }) => project.title === updatedTitle);
  expect(published.featured).toBe(true);
  await page.goto('/');
  await page.getByRole('button', { name: `${updatedTitle} 상세 보기` }).click();
  await expect(page.getByRole('dialog', { name: updatedTitle })).toContainText('프로젝트 등록부터 공개');
  await page.keyboard.press('Escape');
  await page.goto('/admin');
  await page.getByRole('button', { name: `${updatedTitle} 삭제`, exact: true }).click();
  let confirm = page.getByRole('dialog', { name: '이 프로젝트를 삭제할까요?' });
  await expect(confirm).toContainText(updatedTitle);
  await confirm.getByRole('button', { name: '취소', exact: true }).click();
  await expect(page.getByRole('button', { name: updatedTitle, exact: true })).toBeVisible();
  await page.getByRole('button', { name: `${updatedTitle} 삭제`, exact: true }).click();
  confirm = page.getByRole('dialog', { name: '이 프로젝트를 삭제할까요?' });
  await confirm.getByRole('button', { name: '프로젝트 삭제', exact: true }).click();
  await expect(confirm).not.toBeVisible();
  await expect(page.locator('.admin-project-row')).toHaveCount(4);
  projects = await (await page.request.get('/api/projects')).json();
  expect(projects.projects.some((project: { title: string }) => project.title === updatedTitle)).toBe(false);
  await page.getByRole('button', { name: '로그아웃', exact: true }).click();
  await page.getByLabel('관리자 비밀번호', { exact: true }).fill('incorrect-test-password');
  await page.getByRole('button', { name: '관리자 로그인' }).click();
  await expect(page.getByRole('alert')).toContainText('비밀번호를 확인해 주세요.');
  await page.getByLabel('관리자 비밀번호', { exact: true }).fill(password);
  await page.getByRole('button', { name: '관리자 로그인' }).click();
  await expect(page.locator('.admin-project-row')).toHaveCount(4);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('public API failure offers a retry which restores projects', async ({ page }) => {
  let failing = true;
  await page.route('**/api/projects', async route => {
    if (failing) await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '테스트 연결 오류' }) });
    else await route.continue();
  });
  await page.goto('/');
  await expect(page.getByRole('alert')).toContainText('테스트 연결 오류');
  failing = false;
  await page.getByRole('button', { name: '다시 불러오기' }).click();
  await expect(page.locator('.project-card')).toHaveCount(4);
  await expect(page.getByRole('alert')).not.toBeVisible();
});
